# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyladies_harare', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pyladies_harare.Category'),
            preserve_default=False,
        ),
    ]
