# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pyladies_harare', '0003_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='full name')),
                ('email', models.CharField(max_length=120, verbose_name='email address')),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyladies_harare.Post')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='meetup',
            name='fromdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='From date'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='todate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='To date'),
        ),
    ]
